# fly.toml app configuration file generated for nyan-helsing-y on 2024-03-11T17:50:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nyan-helsing-y'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 1234
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
